<!DOCTYPE html>
<html ng-app="AshcorpApp" ng-controller="CoreController">
    <head>
        <?php include View::Partial("head"); ?>
    </head>
    <body ng-app="AshcorpApp" ng-controller="UserController" ng-init="Controller.InitLogin();">
        <section class="form7 cid-seDDYJbDFT" id="form7-1r">
            <div class="container">
                <div class="mbr-section-head">
                    <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                        <strong>Login</strong>
                    </h3>
                </div>
                <div class="row justify-content-center mt-4">
                    <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
                        <form action="/" method="POST" class="mbr-form form-with-styler mx-auto" data-form-title="Login">
                            <p class="mbr-text mbr-fonts-style align-center mb-4 display-7">
                                Welcome to <?php echo Config::SiteName(); ?>
                            </p>
                            <div class="dragArea row">
                                <div class="col-lg-12 col-md-12 col-sm-12 form-group" data-for="email">
                                    <input type="email" name="email" placeholder="Email" data-form-field="email" class="form-control" ng-model="Controller.user.email" id="email-form7-1r">
                                </div>
                                <div data-for="phone" class="col-lg-12 col-md-12 col-sm-12 form-group">
                                    <input type="password" name="password" placeholder="Password" data-form-field="password" class="form-control" ng-model="Controller.user.password" id="phone-form7-1r">
                                </div>
                                <div class="col-auto mbr-section-btn align-center">
                                    <button type="button" class="btn btn-primary display-4" ng-click="Controller.Login();">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <?php include View::Partial("foot"); ?>
    </body>
</html>