<section class="content6 cid-sePc1TGLqV" id="content6-1s">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <hr class="line">
                <p class="mbr-text align-center mbr-fonts-style my-4 display-1">Our Core Values</p>
                <hr class="line">
            </div>
        </div>
    </div>
</section>

<section class="content4 cid-sePcV9dJ2z" id="content4-1v">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="title col-md-12 col-lg-11">
                <h3 class="mbr-section-title mbr-fonts-style align-center mb-4 display-2"><strong>Our Vision</strong></h3>
                <h4 class="mbr-section-subtitle align-center mbr-fonts-style mb-4 display-7">
                    As we move to an ever more digitally connected world, we are at the forefront of business processes. 
                    Innovating and streamlining the systems that will shape the future of business to fit their requirement.
                </h4>
            </div>
        </div>
    </div>
</section>

<section class="content4 cid-sePcW5kN4V" id="content4-1w">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="title col-md-12 col-lg-11">
                <h3 class="mbr-section-title mbr-fonts-style align-center mb-4 display-2"><strong>Our Mission</strong></h3>
                <h4 class="mbr-section-subtitle align-center mbr-fonts-style mb-4 display-7">
                    We innovate and streamline business processes for maximum efficiency. 
                    We do this for all forward thinking local business owners who understand that the system is the solution. 
                    We accomplish this by teaching and inspiring our team to better assist our clients, and by providing our clients with the resources needed to move forward.
                </h4>
            </div>
        </div>
    </div>
</section>

<section class="content4 cid-sePcWo5nWK" id="content4-1x">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="title col-md-12 col-lg-11">
                <h3 class="mbr-section-title mbr-fonts-style align-center mb-4 display-2"><strong>We stick around</strong></h3>
                <h4 class="mbr-section-subtitle align-center mbr-fonts-style mb-4 display-7">
                    When you choose us as your service provider we stick around and manage your account and the Online Assistant.
                    We don’t leave you to the vast abyss of the internet, to deal with vanishing Online Assistants who take your money and your work.
                    We have Account Managers who are in constant contact with the Online Assistants to ensure quality service. 
                    If you find our services unsatisfactory you may escalate to the CEO directly and appropriate measures will be taken.
                    The Online Assistants who work for us are like family. 
                    We love our Online Assistants and we know you will love them as well.
                </h4>
            </div>
        </div>
    </div>
</section>

<section class="content4 cid-sePcWo5nWK" id="content4-1y">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="title col-md-12 col-lg-11">
                <h3 class="mbr-section-title mbr-fonts-style align-center mb-4 display-2"><strong>Our commitment to Mauritius</strong></h3>
                <h4 class="mbr-section-subtitle align-center mbr-fonts-style mb-4 display-7">
                    Mauritius counts a considerable number of educated people who lack opportunities. The foreign industries such as BPO industries (Business Process Outsourcing) implemented in Mauritius for decades show their interest and trust in Mauritian people to work remotely for them not only for cheap labour but also for the high level of education in Mauritius.
                    <br/><br/>
                    <u>This is where the Emers family story begins…</u>
                    <br/><br/>
                    Our CEO spent almost 10 years managing a community team of remote Admin Assistant working for both start-ups and well established foreign companies which she handled with great passion and enthusiasm, and wants our country to benefit from the same services. Emers Outsourcing Ltd is more than happy to offer the opportunities to the Mauritian people to use both their skills and education at the service of the nation and local industries. We show our commitment to them by paying an above industry standard wage and offer advancement opportunities for those wanting to achieve more. We take a real interest in the further development of our Online Assistants by offering industry certifications at no cost to them. We educate, teach, and inspire our Online Assistants to be the best. We are also offering you the opportunity to enjoy these outstanding services from our local people at affordable prices.
                    <br/><br/>
                    Choose us as your service provider and see the difference.
                </h4>
            </div>
        </div>
    </div>
</section>