<section class="form5 cid-seMWYuc4ZY" id="form5-12" ng-app="AshcorpApp" ng-controller="ContactController" ng-init="Controller.Init();">
    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong>Get In Touch</strong>
            </h3>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
                <form class="mbr-form form-with-styler" data-form-title="Form Name">
                    <div class="dragArea row">
                        <div class="col-md col-sm-12 form-group" data-for="name">
                            <input type="text" name="name" ng-model="Controller.contact.name" placeholder="Name" data-form-field="name" class="form-control" value="" id="name-form5-12">
                        </div>
                        <div class="col-md col-sm-12 form-group" data-for="email">
                            <input type="email" name="email" ng-model="Controller.contact.email" placeholder="E-mail" data-form-field="email" class="form-control" value="" id="email-form5-12">
                        </div>
                        <div class="col-12 form-group" data-for="url">
                            <input type="text" name="phone" pattern="[0-9]{7,8}" ng-model="Controller.contact.phone" placeholder="Phone" data-form-field="phone" class="form-control" value="" id="url-form5-12">
                        </div>
                        <div class="col-12 form-group" data-for="textarea">
                            <textarea name="textarea" ng-model="Controller.contact.message" placeholder="Message" data-form-field="textarea" class="form-control" id="textarea-form5-12"></textarea>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 align-center mbr-section-btn">
                            <button type="button" ng-click="Controller.Contact();" class="btn btn-primary display-4">Send message</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<section class="contacts2 cid-seMX9HZgAZ" id="contacts2-13">
    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong>Contacts</strong>
            </h3>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="card col-12 col-md-6">
                <div class="card-wrapper">
                    <div class="image-wrapper">
                        <span class="mbr-iconfont mobi-mbri-phone mobi-mbri"></span>
                    </div>
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style mb-1 display-5">
                            <strong>Phone</strong>
                        </h6>
                        <p class="mbr-text mbr-fonts-style display-7">+230 218 44 15</p>
                    </div>
                </div>
            </div>
            <div class="card col-12 col-md-6">
                <div class="card-wrapper">
                    <div class="image-wrapper">
                        <span class="mbr-iconfont mobi-mbri-letter mobi-mbri"></span>
                    </div>
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style mb-1 display-5">
                            <strong>Email</strong>
                        </h6>
                        <p class="mbr-text mbr-fonts-style display-7">
                            <a href="mailto:info@e-mersoutsourcing.com" class="text-primary">info@e-mersoutsourcing.com</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="card col-12 col-md-6">
                <div class="card-wrapper">
                    <div class="image-wrapper">
                        <span class="mbr-iconfont mobi-mbri-globe mobi-mbri"></span>
                    </div>
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style mb-1 display-5">
                            <strong>Location</strong></h6>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Mauritius</p>
                    </div>
                </div>
            </div>
            <div class="card col-12 col-md-6">
                <div class="card-wrapper">
                    <div class="image-wrapper">
                        <span class="mbr-iconfont mobi-mbri-bulleted-list mobi-mbri"></span>
                    </div>
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style mb-1 display-5">
                            <strong>Working Hours</strong>
                        </h6>
                        <p class="mbr-text mbr-fonts-style display-7">
                            9:00 - 17:00
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>