<section class="content17 cid-sePKDdFgSH" id="content17-2v">

    <div class="container-fluid">

        <div class="row justify-content-center">
            <div class="col-12 col-md-11">
                <div class="section-head align-center mb-4">
                    <h3 class="mbr-section-title mb-0 mbr-fonts-style display-2"><strong>Getting Started</strong></h3>
                </div>
                <div id="bootstrap-toggle" class="toggle-panel accordionStyles tab-content">
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingOne">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse1_27" aria-expanded="false" aria-controls="collapse1">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>How soon can you start the work?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse1_27" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">Your Online Assistant will contact you and start the work within one business day from the time you signed the contract.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingTwo">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse2_27" aria-expanded="false" aria-controls="collapse2">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Can I cancel anytime? Is there any contract?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>

                        </div>
                        <div id="collapse2_27" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingTwo">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">No. You will sign a 12 months contract valid for the same period of time.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingThree">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse3_27" aria-expanded="false" aria-controls="collapse3">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>I just signed. What’s next?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse3_27" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">Based on your requirements, please give us one business day for the set up. Once you are assigned a team member of your Online Assistant services, we will email you. Your Online Assistant will start the work within one business day from the time you signed the contract.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingThree">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse4_27" aria-expanded="false" aria-controls="collapse4">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Do you have a set up fee?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse4_27" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">
                                    We charge a set up fee for the dedicated line option ONLY.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingThree">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse5_27" aria-expanded="false" aria-controls="collapse5">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Will I be assigned a dedicated assistant?</strong></h6>
                                <span class="mbr-iconfont mobi-mbri-arrow-down mobi-mbri"></span>
                            </a>
                        </div>
                        <div id="collapse5_27" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">
                                    Of course. You will get an experienced dedicated Online Assistant with back up. Your dedicated Online Assistant will be available Monday-Friday between 9 AM – 5 PM. You can phone/video call/chat with your virtual assistant anytime during the business hours.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingThree">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse6_27" aria-expanded="false" aria-controls="collapse6">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Will my Online Assistant be able to assist all my customers?</strong></h6>
                                <span class="mbr-iconfont mobi-mbri-arrow-down mobi-mbri"></span>
                            </a>
                        </div>
                        <div id="collapse6_27" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">
                                    Yes, our Online Assistants are Creole, French and English speakers.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content17 cid-sePMLVBjX6" id="content17-2x">





    <div class="container-fluid">

        <div class="row justify-content-center">
            <div class="col-12 col-md-11">
                <div class="section-head align-center mb-4">
                    <h3 class="mbr-section-title mb-0 mbr-fonts-style display-2"><strong>Online Assistants</strong></h3>

                </div>

                <div id="bootstrap-toggle" class="toggle-panel accordionStyles tab-content">
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingOne">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse1_28" aria-expanded="false" aria-controls="collapse1">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Where will my Online Assistant be located?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse1_28" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">Your Online Assistant will be located in Mauritius itself.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingTwo">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse2_28" aria-expanded="false" aria-controls="collapse2">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>How many years of experience will my Online Assistant have?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>

                        </div>
                        <div id="collapse2_28" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingTwo">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">All our Online Assistants have been helping entrepreneurs, business owners, real estate agents and executives for at least 5 years.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content17 cid-sePNo2qVlC" id="content17-2y">
    <div class="container-fluid">

        <div class="row justify-content-center">
            <div class="col-12 col-md-11">
                <div class="section-head align-center mb-4">
                    <h3 class="mbr-section-title mb-0 mbr-fonts-style display-2">
                        <strong>Tasks</strong>
                    </h3>

                </div>

                <div id="bootstrap-toggle" class="toggle-panel accordionStyles tab-content">
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingOne">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse1_29" aria-expanded="false" aria-controls="collapse1">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Will my Online Assistant attend business/personal phone calls on my behalf?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse1_29" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">Yes, your Online Assistant will attend all your phone calls on your behalf.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingTwo">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse2_29" aria-expanded="false" aria-controls="collapse2">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Can I do a weekly meeting with my Online Assistant?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>

                        </div>
                        <div id="collapse2_29" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingTwo">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">Yes, you can do a weekly or even daily video meeting with your Online Assistant like you do with your in-house employee.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingThree">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse3_29" aria-expanded="false" aria-controls="collapse3">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Can my Online Assistant make outbound phone/sales calls for me?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse3_29" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">Absolutely. All our Online Assistants are trained and experienced sales people too. They are very good at closing deals as well.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingThree">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse4_29" aria-expanded="false" aria-controls="collapse4">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Can my Online Assistant handle scheduling?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse4_29" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">
                                    Of course. Your Online Assistant will schedule appointments, coordinate meetings, and manage your Google Calendar or other calendar applications for you. You just have to grant access to your Online Assistant. They will do the rest for you.</p>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</section>

<section class="content17 cid-sePOEXYVvk" id="content17-2z">
    <div class="container-fluid">

        <div class="row justify-content-center">
            <div class="col-12 col-md-11">
                <div class="section-head align-center mb-4">
                    <h3 class="mbr-section-title mb-0 mbr-fonts-style display-2"><strong>What the Online Assistans can’t help with?</strong></h3>

                </div>

                <div id="bootstrap-toggle" class="toggle-panel accordionStyles tab-content">
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingOne">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse1_30" aria-expanded="false" aria-controls="collapse1">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>24/7 Answering Services</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse1_30" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">Our Online Assistants are happy to receive, make and return calls, but we don’t operate as a full-time call centre.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingTwo">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse2_30" aria-expanded="false" aria-controls="collapse2">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Strategic Consulting</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>

                        </div>
                        <div id="collapse2_30" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingTwo">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">Online Assistants can’t act as business consultants or advise on critical company decisions.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingThree">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse3_30" aria-expanded="false" aria-controls="collapse3">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Web Development</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse3_30" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">Simple website changes are fine – just not a coding overhaul!</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingThree">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse4_30" aria-expanded="false" aria-controls="collapse4">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Graphic Design</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse4_30" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">
                                    Our Online&nbsp;Assistants can manage a rebrand project or create simple social media graphics – but not create complex designs themselves.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingThree">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse5_30" aria-expanded="false" aria-controls="collapse5">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Storing &amp; Sending Goods</strong></h6>
                                <span class="mbr-iconfont mobi-mbri-arrow-down mobi-mbri"></span>
                            </a>
                        </div>
                        <div id="collapse5_30" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">
                                    But our Online Assistants&nbsp;can arrange the necessary third party services.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingThree">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse6_30" aria-expanded="false" aria-controls="collapse6">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>No Spams</strong></h6>
                                <span class="mbr-iconfont mobi-mbri-arrow-down mobi-mbri"></span>
                            </a>
                        </div>
                        <div id="collapse6_30" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">Our&nbsp;Online Assistants can’t help with cold calling campaigns or sending spam emails.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content17 cid-sePQPmndsD" id="content17-30">





    <div class="container-fluid">

        <div class="row justify-content-center">
            <div class="col-12 col-md-11">
                <div class="section-head align-center mb-4">
                    <h3 class="mbr-section-title mb-0 mbr-fonts-style display-2">
                        <strong>Payment</strong>
                    </h3>

                </div>

                <div id="bootstrap-toggle" class="toggle-panel accordionStyles tab-content">
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingOne">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse1_31" aria-expanded="false" aria-controls="collapse1">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>Do you have any other hidden charges?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse1_31" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">We don’t have any other charges than those mentionned in your contract.</p>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-header" role="tab" id="headingTwo">
                            <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href="#collapse2_31" aria-expanded="false" aria-controls="collapse2">
                                <h6 class="panel-title-edit mbr-fonts-style mb-0 display-7"><strong>What is your refund policy?</strong></h6>
                                <span class="sign mbr-iconfont mbri-arrow-down"></span>
                            </a>
                        </div>
                        <div id="collapse2_31" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingTwo">
                            <div class="panel-body">
                                <p class="mbr-fonts-style panel-text display-7">We allocate resources for the hours set. It works the same as in-house employees. Whether you give him work or not, he will still get paid until you release him as he allocates time for you. Therefore, since you signed for a 12 months agreement and pay in arrears, only deposit will be refunded automatically within 4-5 business days after termination of your agreement as per our business policy.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

