<section class="features9 cid-sePl8PnaIU" id="features10-2h">
    <div class="container">
        <div class="row mt-4">
            <div class="card col-12">
                <div class="card-wrapper">
                    <div class="top-line row">
                        <div class="col">
                            <h4 class="card-title mbr-fonts-style display-5"><strong>What is an Online Assistant?</strong><br></h4>
                        </div>
                        <div class="col-auto">
                            <p class="price mbr-fonts-style display-5"></p>
                        </div>
                    </div>
                    <div class="bottom-line">
                        <p class="mbr-text mbr-fonts-style display-7">An Online Assistant is an office administration professional offering remote administrative support to any businesses.</p>
                    </div>
                </div>
            </div>
            <div class="card col-12">
                <div class="card-wrapper">
                    <div class="top-line row">
                        <div class="col">
                            <h4 class="card-title mbr-fonts-style display-5"><strong>Why you need it?</strong></h4>
                        </div>
                        <div class="col-auto">
                            <p class="price mbr-fonts-style display-5"></p>
                        </div>
                    </div>
                    <div class="bottom-line">
                        <p class="mbr-text mbr-fonts-style display-7">Do you have an overflow of work that needs to be done? Have you considered an Online Assistant? Providing quality administrative services remotely allowing you to concentrate on what makes your business great!</p>
                    </div>
                </div>
            </div>
            <div class="card col-12">
                <div class="card-wrapper">
                    <div class="top-line row">
                        <div class="col">
                            <h4 class="card-title mbr-fonts-style display-5"><strong>Why do we use it?</strong></h4>
                        </div>
                        <div class="col-auto">
                            <p class="price mbr-fonts-style display-5"></p>
                        </div>
                    </div>
                    <div class="bottom-line">
                        <p class="mbr-text mbr-fonts-style display-7">No payroll, no tax complications, no benefits, no paid holidays and no headache.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="features11 cid-seIKwNri8s" id="features12-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-lg">
                <div class="card-wrapper">
                    <div class="card-box">
                        <h4 class="card-title mbr-fonts-style mb-4 display-2"><strong>FOCUS ON HIGH PRIORITY TASKS</strong></h4>
                        <p class="mbr-text mbr-fonts-style mb-4 display-7">Hire An Online Assistant TODAY!
                            <br>
                            <br>An specialised Online Assistant will save you time and allow you to focus more on travelling, family, or on your business!
                            <br>
                            <br>Allow your Online Assistant to take on those daily, repetitive tasks so that you can focus on other things!
                            <br>
                            <br>Its incredibly easy and cost effective.</p>


                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6 md-pb">
                <div class="image-wrapper">
                    <img src="assets/images/3.jpg" alt="Mobirise">
                </div>
            </div>
        </div>
    </div>
</section>

<section class="features19 cid-seIKAs9t9o" id="features20-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9">
                <div class="card-wrapper pb-4">
                    <div class="card-box align-center">
                        <h4 class="card-title mbr-fonts-style mb-4 display-2"><strong>Can Your Tasks Be Done Remotely?</strong></h4>
                        <p class="mbr-text mbr-fonts-style mb-4 display-7">Do you need help but don’t want to hire a full-time employee that you’ll need to babysit, provide an office for, and keep busy?
                            <br>
                            <br>Online Assistants can work from anywhere, are there when you need them, and work your way.
                            <br>
                            <br>Many of the tasks you do daily are things that someone else can do remotely for you. If you are doing the same things day to day on a computer or over the phone, chances are you can delegate those tasks to someone remotely.
                            <br>
                            <br>Our Online Assistants are here to the rescue!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content6 cid-seIKFkDwGW" id="content6-6">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <hr class="line">
                <p class="mbr-text align-center mbr-fonts-style my-4 display-5">How Can Emers Team  Help?</p>
                <hr class="line">
            </div>
        </div>
    </div>
</section>

<section class="content5 cid-seIO1FCQsI" id="content5-9">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <p class="mbr-text mbr-fonts-style display-7">
                    Our team of Online Assistants are skilled in many different areas. This allows us to help you in almost every facet of your company. Our services includes the more common tasks for your business needs with options to fit your additional requirements. Don't worry about limitations.<br><br><strong>We are the solution!</strong><br><br></p>
            </div>
        </div>
    </div>
</section>