
<section class="content4 cid-seTbaDxGx8" id="content4-39">
    <div class="container">
        <div class="row justify-content-center">
            <div class="title col-md-12 col-lg-10">
                <h4 class="mbr-section-subtitle align-center mbr-fonts-style mb-4 display-7">There are currently no vacancies available! 
                    <div>Please come back soon.</div>
                </h4>
            </div>
        </div>
    </div>
</section>