<section class="features10 cid-seOC6bQtbJ" id="features11-1h">
    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style mb-0 display-2">OUR SERVICES</h3>
        </div>
        <div class="row mt-4">
            <div class="card col-12">
                <div class="card-wrapper">
                    <div class="top-line row">
                        <div class="col">
                            <h4 class="card-title mbr-fonts-style display-5"><strong>Customer Service</strong><br></h4>
                        </div>
                        <div class="col-auto">
                            <p class="price mbr-fonts-style display-5"></p>
                        </div>
                    </div>
                    <div class="bottom-line">
                        <p class="mbr-text mbr-fonts-style display-7">Focus your time on sales, marketing, systems, efficiency, and the like, and let your Online Assistant handle your calls and provide excellent customer service.</p>
                    </div>
                </div>
            </div>
            <div class="card col-12">
                <div class="card-wrapper">
                    <div class="top-line row">
                        <div class="col">
                            <h4 class="card-title mbr-fonts-style display-5"><strong>Admin Support</strong></h4>
                        </div>
                        <div class="col-auto">
                            <p class="price mbr-fonts-style display-5"></p>
                        </div>
                    </div>
                    <div class="bottom-line">
                        <p class="mbr-text mbr-fonts-style display-7">
                            Allow your Online Assistant handle the day to day repetitive tasks and admin duties of your business while you focus on growing on your business, spending time with family, or traveling.
                        </p>
                    </div>
                </div>
            </div>
            <div class="card col-12">
                <div class="card-wrapper">
                    <div class="top-line row">
                        <div class="col">
                            <h4 class="card-title mbr-fonts-style display-5"><strong>Data Entry</strong></h4>
                        </div>
                        <div class="col-auto">
                            <p class="price mbr-fonts-style display-5"></p>
                        </div>
                    </div>
                    <div class="bottom-line">
                        <p class="mbr-text mbr-fonts-style display-7">
                            Let your Online Assistant handle the simple, yet necessary tasks of updating medical records, or entering information on sales leads. They may even log billing info for customers or create new user profiles.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>