<section class="features9 cid-sePl8PnaIU" id="features10-2h">
    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style mb-0 display-2">Ready to get more done?</h3>
        </div>
        <div class="row mt-4">
            <div class="card col-12">
                <div class="card-wrapper">
                    <div class="top-line row">
                        <div class="col">
                            <h4 class="card-title mbr-fonts-style display-5"><strong>Our Guarantee</strong><br></h4>
                        </div>
                        <div class="col-auto">
                            <p class="price mbr-fonts-style display-5"></p>
                        </div>
                    </div>
                    <div class="bottom-line">
                        <p class="mbr-text mbr-fonts-style display-7">We can assure you that all the Online Assistants we have are tried, tested and experienced. We train them specially not to lose their cool under pressure and we mould them up in such a way that they are adaptive to any sort of hectic situation.&nbsp;<br><br>We will be available during your business hours and return your call within 15 minutes if we miss your call. We will save at least 75% of your time and improve your profit.&nbsp;</p>
                    </div>
                </div>
            </div>
            <div class="card col-12">
                <div class="card-wrapper">
                    <div class="top-line row">
                        <div class="col">
                            <h4 class="card-title mbr-fonts-style display-5"><strong>Our flat-rate pricing</strong></h4>
                        </div>
                        <div class="col-auto">
                            <p class="price mbr-fonts-style display-5"></p>
                        </div>
                    </div>
                    <div class="bottom-line">
                        <p class="mbr-text mbr-fonts-style display-7">Our pricing is the lowest in the industry for the level of services offering to you. Our services is about half the cost of industry standard wages in Mauritius and a quarter than an in-office employee will cost you.<br></p>
                    </div>
                </div>
            </div>
            <div class="card col-12">
                <div class="card-wrapper">
                    <div class="top-line row">
                        <div class="col">
                            <h4 class="card-title mbr-fonts-style display-5"><strong>Significantly reduced equipment costs</strong></h4>
                        </div>
                        <div class="col-auto">
                            <p class="price mbr-fonts-style display-5"></p>
                        </div>
                    </div>
                    <div class="bottom-line">
                        <p class="mbr-text mbr-fonts-style display-7">Almost all staff members working in office&nbsp;require access to a computer, phone line and internet to complete their day to day tasks. Supplying an entire workforce is costly, considering you have to factor in maintenance cost and rental cost. With our Online Assistants, there is no need to provide any equipment as we supply our own and this can seriously slash your equipment costs.
                            <br>
                            <br>If we fail to deliver any of these promises, please let us know.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
